### ISSUE TITLE
Syntactic symbols are conflated with standard library functions in tooltips

### ISSUE THREAD

**Issue by CraigFe** [ocamllabs/vscode-ocaml-platform#654]
Given the following code sample:

```
module X = struct end
```

Hovering over the `=` symbol shows a tooltip explaining structural equality, as if `( = )` were appearing in an expression:

![image](https://user-images.githubusercontent.com/26125912/124329560-8a27e080-db83-11eb-806b-508c78cc7fdc.png)

Interestingly, the `=` symbols in type definitions aren't affected in the same way. They display information about the `Stdlib` module instead:

```
type x = < >
```

![image](https://user-images.githubusercontent.com/26125912/124329922-3ff32f00-db84-11eb-8eeb-2dcd42c33a04.png)

(In this case, it would seem better not to print a tooltip at all.)

Hovering over the `<` instead leads to a tooltip about polymorphic comparison:

![image](https://user-images.githubusercontent.com/26125912/124330100-a5dfb680-db84-11eb-8c1e-eaed288e9353.png)

Overall, it seems that the tooltips are prone to misinterpreting various bits of OCaml syntax as infix operators.

---

Versions:

`vscode-ocaml-platform`: 1.8.4
`ocamllsp`: 1.6.1

**Comment by ulugbekna** [comment]
> Interestingly, the = symbols in type definitions aren't affected in the same way. They display information about the Stdlib module instead:

That should be a case of https://github.com/ocaml/ocaml-lsp/issues/344, which potentially will be fixed by https://github.com/ocaml/merlin/pull/1339

---

re: hovering over `=`, `<` symbols is incorrect

I tried this with merlin and have the same problem, so either that's a merlin bug or we're passing wrong args to merlin, which prevent its correct work 

```
$ ocamlmerlin single document -position 1:6 -filename test.ml <<EOF
   let a = ()
   EOF
{
  "class":"return",
  "value":" [e1 = e2] tests for structural equality of [e1] and [e2].\n   Mutable structures (e.g. references and arrays) are equal\n   if and only if their current contents are structurally equal,\n   even if the two mutable objects are not the same physical object.\n   Equality between functional values raises [Invalid_argument].\n   Equality between cyclic data structures may not terminate.\n   Left-associative operator, see {!Ocaml_operators} for more information. ",
  "notifications":[],
  "timing":{"clock":20,"cpu":7,"query":3,"pp":0,"reader":1,"ppx":0,"typer":2,"error":0}
}
```

**Comment by tmattio** [comment]
@ulugbekna I think this has been fixed in the latest ocaml-lsp?

**Comment by ulugbekna** [comment]
No, we still get documentation for syntactic symbols.

**Comment by smorimoto** [comment]
Confirmed upstream. This extension delegates standard hover to `ocamllsp`, and Merlin’s own `document` query returns operator documentation for these syntax tokens. `ocamllsp` now filters the `=` cases via https://github.com/ocaml/ocaml-lsp/pull/1245, but the `<` case still reproduces in 1.27.0. Related history: https://github.com/ocaml/ocaml-lsp/issues/344 and https://github.com/ocaml/merlin/pull/1339. Closing here.
